services:
  execution:
    build:
      context: .
      dockerfile: ${CLIENT:-geth}/Dockerfile
    restart: unless-stopped
    ports:
      - "8545:8545" # RPC
      - "8546:8546" # websocket
      - "7301:6060" # metrics
      - "30303:30303" # P2P TCP
      - "30303:30303/udp" # P2P UDP
    command: ["bash", "./execution-entrypoint"]
    volumes:
      - /node/reth-data:/data
    env_file:
      - ${NETWORK_ENV:-.env.mainnet} # Use .env.mainnet by default, override with .env.sepolia for testnet
    labels:
      - traefik.enable=true
      - traefik.docker.network=agoo8w44c08o0goocc0cs0wk

      # JSON-RPC HTTPS → rpc.arcadia.finance (port 8545)
      - traefik.http.routers.rpc.rule=Host(`rpc.arcadia.finance`)
      - traefik.http.routers.rpc.entrypoints=websecure
      - traefik.http.routers.rpc.tls.certresolver=letsencrypt
      - traefik.http.services.rpc.loadbalancer.server.port=8545

      # WSS WebSocket → ws.rpc.arcadia.finance (port 8546)
      - traefik.http.routers.ws-rpc.rule=Host(`ws.rpc.arcadia.finance`)
      - traefik.http.routers.ws-rpc.entrypoints=websecure
      - traefik.http.routers.ws-rpc.tls.certresolver=letsencrypt
      - traefik.http.services.ws-rpc.loadbalancer.server.port=8546
  node:
    build:
      context: .
      dockerfile: ${CLIENT:-geth}/Dockerfile
    restart: unless-stopped
    depends_on:
      - execution
    ports:
      - "7545:8545" # RPC
      - "9222:9222" # P2P TCP
      - "9222:9222/udp" # P2P UDP
      - "7300:7300" # metrics
      - "6060:6060" # pprof
    command: ["bash", "./op-node-entrypoint"]
    env_file:
      - ${NETWORK_ENV:-.env.mainnet} # Use .env.mainnet by default, override with .env.sepolia for testnet
